export const LOGIN_USER_SUCCESS = 'users/loginSuccess'
export const DETAIL_TRANSACTION_SUCCESS = 'transactions/getDetailSuccess'
export const GET_CATEGORIES_SUCCESS = 'transactions/getCategoriesSuccess'
export const DETAIL_USER_SUCCESS = 'users/detailSuccess'
export const SAVE_HISTORY_SUCCESS = 'consultant/saveHistory'